const mongoose=require('mongoose')
const userSchema=mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true 
    },
    mobile:{
        type:Number,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    is_admin:{
        type:Number,
        default:0
    },
    is_active:{
        type:Boolean,
        default:true
    },
    date:{
        type:Date,
        default:Date.now
    },
    otp:{
        type:Number,
        default:null
    },
    address:[
        {
            fname:{
                type:String
            },
            lname:{
                type:String
            },
            country:{
                type:String
            },
            housename:{
                type:String,               
            },
            city:{
                type:String
            },
            state:{
                type:String
            },
            pincode:{
                type:Number
            },
            phone:{
                type:Number
            },
            email:{
                type:String
            },
            description:{
                type:String
            }

        }
    ],
    cart:[
        {
            productId:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'Product'
            },
            quantity:{
                type:Number,
                default:1
            }
        }
    ],
    wallet:{
        type:Number,
        default:0
    },
    referralCode:{
        type:String
    }
})

module.exports=mongoose.model('User',userSchema) 